### ISSUE TITLE
Allow nullable values with HasMany and HasOne strategies

### ISSUE THREAD

**Issue by leogr** [matryoshka-model/matryoshka#23]
Currently those strategies (`HasMany` and `HasOne`) do not allow null values to pass through.
That's useful when user want to allow that a property's value can be an embedded object (or a collection of them) or null.
For instance, it is very useful when the signature of a setter method has type hint with null value allowed.
E.g.,

```php
public function setSomething(SomethingInterface $something = null);
```

**Goal**

Strategies should allow to enable this behavior optionally: this behaviour should be not enabled by default (to avoid BCs).

**Side question**

Other strategies allow null values to pass through already. Should it be optional also for them?

**Comment by leodido** [comment]
Currently [DateTimeStrategy](https://github.com/matryoshka-model/matryoshka/blob/develop/library/Hydrator/Strategy/DateTimeStrategy.php) is always nullable.
Should it implement [NullableStrategyInterface](https://github.com/matryoshka-model/matryoshka/blob/develop/library/Hydrator/Strategy/NullableStrategyInterface.php)?
